name: "Hello Actions"
description: "Greet someone"
author: "kon@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
  
runs:
  using: "docker"
  image: "Dockerfile"
  
barnding:
  icon: "mic"
  color: "purple"
